FROM saasglue/sg-agent:latest as kubernetes_job_runner

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

USER appuser

CMD ["./sg-agent-launcher"]
